SET @FECHACORTE = '2020-06-30';
SET @FECHA_INICIO_TXT = (SELECT EstParVal FROM estatutos WHERE EstParCod = 'FINICAS');
SET @FECHA_INICIO = CONCAT(SUBSTRING(@FECHA_INICIO_TXT, 7, 4), '-', SUBSTRING(@FECHA_INICIO_TXT, 4, 2), '-', SUBSTRING(@FECHA_INICIO_TXT, 1, 2));
SET @FECHA_ANTERIOR = LAST_DAY(DATE_ADD(@FECHACORTE, INTERVAL -1 MONTH));
SET @CODIGO_SUSCRIPTOR = (SELECT EstParVal FROM estatutos WHERE EstParCod = 'DATACRE');
SELECT @FECHA_ANTERIOR, @FECHA_INICIO_TXT, @FECHA_INICIO, @CODIGO_SUSCRIPTOR ;

-- CARTERA DEUDORES VIGENTES
DROP TABLE IF EXISTS VIGENTES;
CREATE TEMPORARY TABLE VIGENTES
SELECT AsoTipIde RPTCOL1, AsoIde RPTCOL2, CieCarCarCod RPTCOL3,
	TRIM(CONCAT(IF(ASOPRIAPE IS NULL, ' ', ASOPRIAPE), ' ', IF(ASOSEGAPE IS NULL, ' ', ASOSEGAPE),' ',IF(ASOPRINOM IS NULL, '', ASOPRINOM), ' ', IF(ASOSEGNOM IS NULL, '',ASOSEGNOM)) ) RPTCOL4,
    0 RPTCOL5, FecDesCre RPTCOL6, FecVenCre RPTCOL7, "00" RPTCOL8, "" RPTCOL9, 0 RPTCOL10,
    1 RPTCOL11, 0 RPTCOL12, 1 RPTCOL13, CieCarDiaMor RPTCOL14,
    CASE WHEN CARCODREE = '' THEN 0 ELSE 2 END RPTCOL15,
    FecDesCre RPTCOL16, CASE WHEN CieCarDiaMor = 0 THEN "01" ELSE "02" END RPTCOL17, @FECHACORTE RPTCOL18, 0 RPTCOL19,
    "00000000" RPTCOL20, 0 RPTCOL21, "00000000" RPTCOL22, 0 RPTCOL23, 0 RPTCOL24, "" RPTCOL25,
    1 RPTCOL26, 0 RPTCOL27, CieCarEXCAR RPTCOL28, "000" RPTCOL29, CieCarDiaMor RPTCOL30,
    ROUND(SALINICRE/1000, 0) RPTCOL31, ROUND(CieCarSalAct/1000, 0) RPTCOL32, "00000000000" RPTCOL33,
    ROUND(ValCuo/1000, 0) RPTCOL34, CieCarValCapMor RPTCOL35, SOLCREPLA RPTCOL36, ALTCRE RPTCOL37,
    CieCarNCMor RPTCOL38, "000" RPTCOL39, "00000000" RPTCOL40, "1000-01-01" RPTCOL41,
    "0000000000" RPTCOL42, SucNom RPTCOL43, SucNom RPTCOL44, MunCod RPTCOL45,
    '' RPTCOL46, AsoLugRes RPTCOL47, "" RPTCOL48, AsoDir RPTCOL49, AsoCel RPTCOL50,
    "" RPTCOL51, AsoDLMun RPTCOL52, "" RPTCOL53, AsoDLDir RPTCOL54, AsoDLTel1 RPTCOL55,
    "" RPTCOL56, AsoLugRes RPTCOL57, "" RPTCOL58,
    AsoDir RPTCOL59, AsoEmail RPTCOL60, AsoCel RPTCOL61, @CODIGO_SUSCRIPTOR RPTCOL62,
    "000000000000000000" RPTCOL63, CarPagVarTga RPTCOL64, "" RPTCOL65,
    -- CAMPOS PARA CONEXION DE CONSULTAS
    1 INDICADOR, AltCre
FROM ciecar C
INNER JOIN asociados A ON C.CieCarAsoCod = A.AsoCod
LEFT JOIN (SELECT MAX(ASODLCOD), DL.* FROM atlantiscoomuldenorteniif.asociadosDL DL GROUP BY ASOCOD) T1 ON A.ASOCOD = T1.ASOCOD
INNER JOIN cartera C2 ON C.CieCarCarCod = C2.CarCod
INNER JOIN SOLCRE S ON C2.SOLCRECOD = S.SOLCRECOD
INNER JOIN SUCURSALES S2 ON S.SolCreSucCod = S2.SUCCOD
WHERE CieCarFecCie = @FECHACORTE;

-- CREDITOS CANCELADOS
INSERT INTO VIGENTES 
SELECT * FROM (
			SELECT AsoTipIde RPTCOL1, AsoIde RPTCOL2, CieCarCarCod RPTCOL3,
				TRIM(CONCAT(IF(ASOPRIAPE IS NULL, ' ', ASOPRIAPE), ' ', IF(ASOSEGAPE IS NULL, ' ', ASOSEGAPE),' ',IF(ASOPRINOM IS NULL, '', ASOPRINOM), ' ', IF(ASOSEGNOM IS NULL, '',ASOSEGNOM)) ) RPTCOL4,
				0 RPTCOL5, FecDesCre RPTCOL6, FecVenCre RPTCOL7, "00" RPTCOL8, "" RPTCOL9, 0 RPTCOL10,
				1 RPTCOL11, 0 RPTCOL12, 1 RPTCOL13, '05' RPTCOL14, 0 RPTCOL15,
				FecDesCre RPTCOL16, "03" RPTCOL17, @FECHACORTE RPTCOL18, 0 RPTCOL19,
				"00000000" RPTCOL20, 0 RPTCOL21, "00000000" RPTCOL22, 0 RPTCOL23, 0 RPTCOL24, "" RPTCOL25,
				1 RPTCOL26, 0 RPTCOL27, CieCarEXCAR RPTCOL28, "000" RPTCOL29, CieCarDiaMor RPTCOL30,
				ROUND(SALINICRE/1000, 0) RPTCOL31, ROUND(CieCarSalAct/1000, 0) RPTCOL32, "00000000000" RPTCOL33,
				ROUND(ValCuo/1000, 0) RPTCOL34, CieCarValCapMor RPTCOL35, SOLCREPLA RPTCOL36, ALTCRE RPTCOL37,
				CieCarNCMor RPTCOL38, "000" RPTCOL39, "00000000" RPTCOL40, "1000-01-01" RPTCOL41,
				"0000000000" RPTCOL42, SucNom RPTCOL43, SucNom RPTCOL44, MunCod RPTCOL45,
				'' RPTCOL46, AsoLugRes RPTCOL47, "" RPTCOL48, AsoDir RPTCOL49, AsoCel RPTCOL50,
				"" RPTCOL51, AsoDLMun RPTCOL52, "" RPTCOL53, AsoDLDir RPTCOL54, AsoDLTel1 RPTCOL55,
				"" RPTCOL56, AsoLugRes RPTCOL57, "" RPTCOL58,
				AsoDir RPTCOL59, AsoEmail RPTCOL60, AsoCel RPTCOL61, @CODIGO_SUSCRIPTOR RPTCOL62,
				"000000000000000000" RPTCOL63, CarPagVarTga RPTCOL64, "" RPTCOL65,
                -- CAMPOS PARA CONEXION DE CONSULTAS
                2 INDICADOR, AltCre
			FROM ciecar C
			INNER JOIN asociados A ON C.CieCarAsoCod = A.AsoCod
			LEFT JOIN (SELECT MAX(ASODLCOD), DL.* FROM atlantiscoomuldenorteniif.asociadosDL DL GROUP BY ASOCOD) T1 ON A.ASOCOD = T1.ASOCOD
			INNER JOIN cartera C2 ON C.CieCarCarCod = C2.CarCod
			INNER JOIN SOLCRE S ON C2.SOLCRECOD = S.SOLCRECOD
			INNER JOIN SUCURSALES S2 ON S.SolCreSucCod = S2.SUCCOD
			WHERE CieCarFecCie = @FECHA_ANTERIOR AND CIECARCARCOD NOT IN (SELECT CIECARCARCOD FROM CIECAR WHERE CieCarFecCie = @FECHACORTE)
		) C;

-- ACTIVOS CASTIGADOS
INSERT INTO VIGENTES 
SELECT * FROM (
			SELECT AsoTipIde RPTCOL1, AsoIde RPTCOL2, ActCasCarCod RPTCOL3,
				TRIM(CONCAT(IF(ASOPRIAPE IS NULL, ' ', ASOPRIAPE), ' ', IF(ASOSEGAPE IS NULL, ' ', ASOSEGAPE),' ',IF(ASOPRINOM IS NULL, '', ASOPRINOM), ' ', IF(ASOSEGNOM IS NULL, '',ASOSEGNOM)) ) RPTCOL4,
				0 RPTCOL5, IFNULL(FecDesCre,  CONCAT(SUBSTRING(ActCasIniCre, 1, 4), '-', SUBSTRING(ActCasIniCre, 5, 2), '-', SUBSTRING(ActCasIniCre, 7, 2))) RPTCOL6,
				IFNULL(FecVenCre,  CONCAT(SUBSTRING(ActCasFinCre, 1, 4), '-', SUBSTRING(ActCasFinCre, 5, 2), '-', SUBSTRING(ActCasFinCre, 7, 2))) RPTCOL7,
				"00" RPTCOL8, "" RPTCOL9, 0 RPTCOL10, 1 RPTCOL11, 0 RPTCOL12, 1 RPTCOL13, '13' RPTCOL14, 0 RPTCOL15,
				IFNULL(FecDesCre,  CONCAT(SUBSTRING(ActCasIniCre, 1, 4), '-', SUBSTRING(ActCasIniCre, 5, 2), '-', SUBSTRING(ActCasIniCre, 7, 2))) RPTCOL16,
				'06' RPTCOL17, '1000-01-01' RPTCOL18, 0 RPTCOL19, "00000000" RPTCOL20, 0 RPTCOL21, "00000000" RPTCOL22, 0 RPTCOL23, 0 RPTCOL24,
				"" RPTCOL25, 1 RPTCOL26, 0 RPTCOL27, ActCasCat RPTCOL28, "000" RPTCOL29, ActCasDiaMor RPTCOL30, ROUND(ActCasSalCap/1000, 0) RPTCOL31,
				0 RPTCOL32, "00000000000" RPTCOL33, 0 RPTCOL34, 0 RPTCOL35, 1 RPTCOL36, 0 RPTCOL37, 0 RPTCOL38, "000" RPTCOL39, "00000000" RPTCOL40,
				ActCasFecCas RPTCOL41, ActCasFecCas RPTCOL42, IFNULL(SucNom, 'CUCUTA') RPTCOL43, IFNULL(SucNom, 'CUCUTA') RPTCOL44,
				IFNULL(MunCod, '54001') RPTCOL45, '' RPTCOL46, AsoLugRes RPTCOL47, "" RPTCOL48, AsoDir RPTCOL49, AsoCel RPTCOL50,
				"" RPTCOL51, AsoDLMun RPTCOL52, "" RPTCOL53, AsoDLDir RPTCOL54, AsoDLTel1 RPTCOL55, "" RPTCOL56, AsoLugRes RPTCOL57,
				"" RPTCOL58, AsoDir RPTCOL59, AsoEmail RPTCOL60, AsoCel RPTCOL61, @CODIGO_SUSCRIPTOR RPTCOL62,
                "000000000000000000" RPTCOL63, IFNULL(CarPagVarTga, 2) RPTCOL64, "" RPTCOL65,
                -- CAMPOS PARA CONEXION DE CONSULTAS
                3 INDICADOR, AltCre
			FROM ACTCAS T1
			INNER JOIN asociados T2 ON T1.ActCasAsoCod = T2.AsoCod
			LEFT JOIN (SELECT MAX(ASODLCOD), DL.* FROM atlantiscoomuldenorteniif.asociadosDL DL GROUP BY ASOCOD) T4 ON T2.ASOCOD = T4.ASOCOD
			LEFT JOIN cartera T3 ON T1.ActCasCarCod = T3.CarCod
			LEFT JOIN SOLCRE S ON T3.SOLCRECOD = S.SOLCRECOD
			LEFT JOIN SUCURSALES S2 ON S.SolCreSucCod = S2.SUCCOD
			WHERE ActCasFecCas >= @FECHA_INICIO AND ActCasFecCas <= @FECHACORTE AND ActCasMod = 'CA' AND ActCasTipCas <> 'E' AND ActcasFecCenRie<> '1753-01-01'
		) C2;

-- CONSULTA LOS CODEUDORES
DROP TABLE IF EXISTS CODEUDORES;
CREATE TEMPORARY TABLE CODEUDORES
SELECT T.SolCreCODTipIde, T.SolCreCODIde, T1.CarCod,
	CASE WHEN T.SolCreCODTip = 'A'
		THEN TRIM(CONCAT(IF(ASOPRIAPE IS NULL, ' ', ASOPRIAPE), ' ', IF(ASOSEGAPE IS NULL, ' ', ASOSEGAPE),' ',IF(ASOPRINOM IS NULL, '', ASOPRINOM), ' ', IF(ASOSEGNOM IS NULL, '',ASOSEGNOM)) )
        ELSE TRIM(CONCAT(IF(CodPriApe IS NULL, ' ', CodPriApe), ' ', IF(CodSegApe IS NULL, ' ', CodSegApe),' ',IF(CodPriNom IS NULL, '', CodPriNom), ' ', IF(CodSegNom IS NULL, '',CodSegNom)) ) END NOMBRE,
        RPTCOL5, RPTCOL6, RPTCOL7, '01' RPTCOL8, RPTCOL9, RPTCOL10, RPTCOL11, RPTCOL12, RPTCOL13, RPTCOL14,
		RPTCOL15, RPTCOL16, RPTCOL17, RPTCOL18, RPTCOL19, RPTCOL20, RPTCOL21, RPTCOL22, RPTCOL23,
		RPTCOL24, RPTCOL25, RPTCOL26, RPTCOL27, RPTCOL28, RPTCOL29, RPTCOL30, RPTCOL31, RPTCOL32,
		RPTCOL33, RPTCOL34, RPTCOL35, RPTCOL36, RPTCOL37, RPTCOL38, RPTCOL39, RPTCOL40, RPTCOL41,
		RPTCOL42, RPTCOL43, RPTCOL44, RPTCOL45, RPTCOL46, RPTCOL47, RPTCOL48, RPTCOL49, RPTCOL50,
		RPTCOL51, RPTCOL52, RPTCOL53, RPTCOL54, RPTCOL55, RPTCOL56, RPTCOL57, RPTCOL58, RPTCOL59,
		RPTCOL60, RPTCOL61, RPTCOL62, RPTCOL63, RPTCOL64, RPTCOL65, 4 INDICADOR, T1.ALTCRE
FROM SOLCRECOD T
INNER JOIN CARTERA T1 ON T.SOLCRECOD = T1.SOLCRECOD
LEFT JOIN CODEUDOR T2 ON T.SolCreCODIde = T2.CodIde AND SolCreCODTip = 'C'
LEFT JOIN ASOCIADOS T3 ON T.SolCreCODIde = T3.ASOIDE AND SolCreCODTip = 'A'
INNER JOIN VIGENTES T4 ON T1.CARCOD = T4.RPTCOL3;

-- INSERTA CDEUDORES
INSERT INTO VIGENTES
SELECT * FROM CODEUDORES;

-- AJUSTAR ESTRUCTURA
ALTER TABLE VIGENTES 
		MODIFY `RPTCOL46` VARCHAR(50) CHARACTER SET utf8  DEFAULT '' NULL,
        MODIFY `RPTCOL48` VARCHAR(50) CHARACTER SET utf8  DEFAULT '' NULL,
        MODIFY `RPTCOL53` VARCHAR(50) CHARACTER SET utf8  DEFAULT '' NULL,
        MODIFY `RPTCOL56` VARCHAR(50) CHARACTER SET utf8  DEFAULT '' NULL,
        MODIFY `RPTCOL58` VARCHAR(50) CHARACTER SET utf8  DEFAULT '' NULL;
        
/***** ACTUALIZACION DE DATOS *****/
-- CREDITOS REESTRUCTURADOS POR ATLANTIS
UPDATE VIGENTES V
INNER JOIN (
		SELECT CARCODREE FROM CARTERA WHERE CARCODREE <> '' GROUP BY CARCODREE
	) T1 ON V.RPTCOL3 = T1.CARCODREE
SET V.RPTCOL15 = 2
WHERE V.INDICADOR <> 3 AND V.RPTCOL15 <> 2;

-- CREDITOS REFINANCIADOS POR ATLANTIS
UPDATE VIGENTES V
INNER JOIN (
		SELECT CARCODREF FROM CARTERA WHERE CARCODREF <> '' GROUP BY CARCODREF
	) T1 ON V.RPTCOL3 = T1.CARCODREF
SET V.RPTCOL15 = 2
WHERE V.INDICADOR <> 3 AND V.RPTCOL15 <> 2;

-- PROXIMA FECHA DE PAGO
UPDATE VIGENTES V
INNER JOIN TABAMOCRE T ON V.RPTCOL3 = T.CARCOD
SET RPTCOL41 = T.TabAmoFPa
WHERE TabAmoNCu = V.ALTCRE+1 AND INDICADOR = 1;

-- ULTIMA FECHA DE PAGO
UPDATE VIGENTES V
INNER JOIN (
		SELECT CarCod, MAX(aFecReaPag) FECHA
		FROM pagoscarteraa
		WHERE aFecReaPag <= @FECHACORTE
		GROUP BY CARCOD
	) T1 ON V.RPTCOL3 = T1.CarCod
SET RPTCOL42 = FECHA;

-- CIUDAD DE LA OBLIGACION
UPDATE VIGENTES V
INNER JOIN MUNICIPIOS M ON M.MUNCOD = V.RPTCOL45
SET V.RPTCOL44 = M.MunNombre;

-- CIUDAD DE RESIDENCIA
UPDATE VIGENTES V
INNER JOIN MUNICIPIOS M ON M.MUNCOD = V.RPTCOL47
SET V.RPTCOL46 = M.MunNombre;

-- DEPARTAMENTO DE RESIDENCIA
UPDATE VIGENTES V
INNER JOIN MUNICIPIOS M ON M.MUNCOD = V.RPTCOL47
INNER JOIN DEPARTAMENTOS D ON M.DEPCOD = D.DEPCOD
SET V.RPTCOL46 = M.MunNombre, V.RPTCOL48 = DepNombre, V.RPTCOL56 = M.MunNombre, V.RPTCOL58 = DepNombre;

-- DEPARTAMENTO LABORAL
UPDATE VIGENTES V
INNER JOIN MUNICIPIOS M ON M.MUNCOD = V.RPTCOL52
INNER JOIN DEPARTAMENTOS D ON M.DEPCOD = D.DEPCOD
SET V.RPTCOL53 = DepNombre;

-- FORMA DE PAGO PARA CREDITOS CANCELADOS VOLUNTARIAMENTE
UPDATE VIGENTES V
INNER JOIN (
			SELECT CarCod COD, MAX(aFecReaPag) FECHA, aNumCuoPK, 1 FORMAPAGO
			FROM pagoscarteraa
			WHERE aFecReaPag <= @FECHACORTE
			GROUP BY CARCOD
		) T ON V.RPTCOL3 = T.COD
SET V.RPTCOL12 = T.FORMAPAGO
WHERE INDICADOR = 2;

-- FORMA DE PAGO Y ESTADO DE LA CUENTA PARA CREDITOS REESTRUCTURADOS O NOVADOS
UPDATE VIGENTES V
INNER JOIN CARTERA C ON V.RPTCOL3 = C.CARCOD
SET RPTCOL12 = '4', RPTCOL17 = "12"
WHERE INDICADOR = 2 AND RPTCOL12 = 1 AND (CARCODREE <> '' OR CARCODREF <> '');

-- ACTUALIZA CREDITOS CASTIGADOS: FORMA DE PAGO - NOVEDAD - FECHA DE LA CUENTA
UPDATE VIGENTES V
INNER JOIN (
		SELECT ActCasCarCod COD, ActCasValCap + ActCasValInt - SUM(ActCasDetValPag) SALDO, MAX(ActCasDetFec) FECHA
		FROM ACTCAS A
		INNER JOIN actcasdet D ON A.ActCasCod = D.ActCasCod
		WHERE ActcasFecCenRie <> '1753-01-01'
		GROUP BY A.ActCasCod
		HAVING SALDO <= 0
	) T ON V.RPTCOL3 = T.COD
-- PAGO VOLUNTARIO - CARTERA RECUPERADA - FECHA DE ULTIMO ABONO
SET RPTCOL12 = 1, RPTCOL14 = '14', RPTCOL18 = FECHA
WHERE INDICADOR = 3;

-- ESTADO DE LA CUENTA PARA CREDITOS CANCELADOS POR ABONO NORMAL O AVANCE A CAPITAL
UPDATE VIGENTES V
INNER JOIN (
			SELECT CarCod COD, MAX(aFecReaPag) FECHA, aNumCuoPK, CASE WHEN aNumCuoPK = 0 THEN "03" ELSE "08" END FORMAPAGO
			FROM pagoscarteraa
			WHERE aFecReaPag <= @FECHACORTE
			GROUP BY CARCOD
		) T ON V.RPTCOL3 = T.COD
SET V.RPTCOL17 = T.FORMAPAGO
WHERE INDICADOR = 2 AND RPTCOL17 <> "12";

-- FECHA ESTADO DE LA CUENTA PARA CREDITOS CANCELADOS
UPDATE VIGENTES
SET RPTCOL18 = RPTCOL42
WHERE INDICADOR = 2;

-- FECHA ESTADO DE LA CUENTA Y SALDO ACTUAL PARA CREDITOS CASTIGADOS
UPDATE VIGENTES V
INNER JOIN (
		SELECT ActCasCarCod COD, ActCasValCap + ActCasValInt - SUM(ActCasDetValPag) SALDO, MAX(ActCasDetFec) FECHA
		FROM ACTCAS A
		INNER JOIN actcasdet D ON A.ActCasCod = D.ActCasCod
		WHERE ActcasFecCenRie <> '1753-01-01'
		GROUP BY A.ActCasCod
		HAVING SALDO > 0
	) T ON V.RPTCOL3 = T.COD
SET RPTCOL18 = FECHA, RPTCOL32 = SALDO, RPTCOL34 = SALDO, RPTCOL35 = SALDO;

-- SE CARGA POR DEFECTO RPTCOL9 = 6 lIBRANZA
-- ACTUALIZAR TIPO DE OBLIGACION PARA CREDITOS DE VIVIENDA  TipCreCod = 3
UPDATE Vigentes T
INNER JOIN
(
	SELECT CARCOD, T3.SolCreCod, TipCreCod   -- DETERMINA CUALES CREDITOS SON CREDITO DE VIVIENDA EJEMPLO 004002008490
	FROM  Cartera T  
	INNER JOIN SolCre T3 ON T.SolCreCod = T3.SolCreCod
	WHERE TipCreCod = 3
)T2
ON T.RPTCOL3 = T2.CARCOD
SET T.RPTCOL9 =3
WHERE INDICADOR <> 3;

-- ACTUALIZAR TIPO DE OBLIGACION PARA CREDITO COMERCIAL Y FORMA DE PAGO CAJA  TipCreCod = 4 Y TipCreVarFPa = 2 EJEMPLO 004003013008
UPDATE VIGENTES T1
INNER JOIN
(
	SELECT  T3.CARCOD CARCOD,T1.TipCreDes,T2.TipCreVarFPa  FROM SOLCRE  T
	INNER JOIN tipocreditos T1 ON T.TipCreCod =T1.TipCreCod 
	INNER JOIN tipocreditosvariable T2 ON T.TipCreCod =T2.TipCreCod AND T.TipCreVarCod = T2.TipCreVarCod
	INNER JOIN CARTERA T3 ON T.SOLCRECOD = T3.SOLCRECOD 
	WHERE T.TipCreCod = 4 AND TipCreVarFPa = 2
) T2
ON T1.RPTCOL3 = T2.CARCOD
SET T1.RPTCOL9 = 1 
WHERE INDICADOR <> 3;

-- ACTUALIZAR TIPO DE OBLIGACION PARA CREDITO CONSUMO Y FORMA DE PAGO CAJA  TipCreCod NOT IN(3, 4) Y TipCreVarFPa = 2 EJEMPLO 
UPDATE VIGENTES T1
INNER JOIN
(
	SELECT  T3.CARCOD CARCOD,T1.TipCreDes,T2.TipCreVarFPa  FROM SOLCRE  T
	INNER JOIN tipocreditos T1 ON T.TipCreCod =T1.TipCreCod 
	INNER JOIN tipocreditosvariable T2 ON T.TipCreCod =T2.TipCreCod AND T.TipCreVarCod = T2.TipCreVarCod
	INNER JOIN CARTERA T3 ON T.SOLCRECOD = T3.SOLCRECOD 
	WHERE T.TipCreCod NOT IN(3, 4) AND TipCreVarFPa = 2
) T2
ON T1.RPTCOL3 = T2.CARCOD
SET T1.RPTCOL9 = 2 
WHERE INDICADOR <> 3;
-- Fin Cambios Estado de Cuenta
SELECT * FROM VIGENTES;

/****** DOCUMENTACION
	-- CAMPOS
	RPTCOL1 = "Tipo de identificación"
	RPTCOL2 = "Número de identificación"
	RPTCOL3 = "Número de cuenta u obligación"
	RPTCOL4 = "Nombre completo"
	RPTCOL5 = "Situación del titular"
	RPTCOL6 = "Fecha de apertura"
	RPTCOL7 = "Fecha de vencimiento"
	RPTCOL8 = "Responsable o calidad de deudor"
	RPTCOL9 = Tipo de obligación"
	RPTCOL10 = "Subsidio hipotecario"
	RPTCOL11 = "Término del contrato que genera la obligación"
	RPTCOL12 = "Forma de pago"
	RPTCOL13 = "Periodicidad de pago"
	RPTCOL14 = "Novedad"
	RPTCOL15 = "Estado origen de la cuenta"
	RPTCOL16 = "Fecha estado origen"
	RPTCOL17 = "Estado de la cuenta"
	RPTCOL18 = "Fecha estado de la cuenta"
	RPTCOL19 = "Estado del plástico"
	RPTCOL20 = "Fecha estado del plástico"
	RPTCOL21 = "Adjetivo"
	RPTCOL22 = "Fecha adjetivo"
	RPTCOL23 = "Clase tarjeta"
	RPTCOL24 = "Franquicia"
	RPTCOL25 = "Nombre marca privada"
	RPTCOL26 = "Tipo de moneda"
	RPTCOL27 = "Tipo de garantía"
	RPTCOL28 = "Calificación"
	RPTCOL29 = "Probabilidad de incumplimiento"
	RPTCOL30 = "Edad de mora"
	RPTCOL31 = "Valor inicial"
	RPTCOL32 = "Saldo deuda"
	RPTCOL33 = "Valor disponible"
	RPTCOL34 = "Valor cuota mensual"
	RPTCOL35 = "Valor saldo en mora"
	RPTCOL36 = "Total cuotas"
	RPTCOL37 = "Cuotas canceladas"
	RPTCOL38 = "Cuotas en mora"
	RPTCOL39 = "Cláusula de permanencia"
	RPTCOL40 = "Fecha cláusula de permanencia"
	RPTCOL41 = "Fecha límite de pago"
	RPTCOL42 = "Fecha de pago"
	RPTCOL43 = "Oficina de radicación"
	RPTCOL44 = "Ciudad de radicación"
	RPTCOL45 = "Código DANE ciudad de radicación"
	RPTCOL46 = "Ciudad de residencia o ciudad comercial"
	RPTCOL47 = "Código DANE ciudad de residencia o ciudad comercial"
	RPTCOL48 = "Departamento de residencia o departamento comercial"
	RPTCOL49 = "Dirección de residencia o dirección comercial"
	RPTCOL50 = "Teléfono de residencia o teléfono comercial"
	RPTCOL51 = "Ciudad laboral"
	RPTCOL52 = "Código DANE ciudad laboral"
	RPTCOL53 = "Departamento laboral"
	RPTCOL54 = "Dirección laboral"
	RPTCOL55 = "Teléfono laboral"
	RPTCOL56 = "Ciudad de correspondencia"
	RPTCOL57 = "Código DANE ciudad de correspondencia"
	RPTCOL58 = "Departamento de correspondencia"
	RPTCOL59 = "Dirección de correspondencia"
	RPTCOL60 = "Correo electrónico"
	RPTCOL61 = "Celular"
	RPTCOL62 = "Suscriptor destino"
	RPTCOL63 = "Número de la tarjeta"
	RPTCOL64 = "Detalle garantía"
	RPTCOL65 = "Filler"
    RPTCOL66 = INDICADOR (	1 = CARTERA - 2 = CANCELADOS - 3 = CASTIGOS)
    
    ESTABLECIDOS
    RPTCOL43 = SE ESTABLECE CUCUTA PARA LOS CASTIGOS MIGRADOS
    RPTCOL44 = SE ESTABLECE CUCUTA PARA LOS CASTIGOS MIGRADOS
    RPTCOL45 = SE ESTABLECE 54001 PARA LOS CASTIGOS MIGRADOS
    
    INDICADOR
	1 = CARTERA
	2 = CANCELADOS
	3 = CASTIGOS
    4 = CODEUDOR
    
    SQL
    INSERT INTO `atlantiscoomuldenorteniif`.`estatutos` (`EstParCod`, `EstParDes`, `EstParVal`) VALUES ('DATACRE', 'CODIGO SUSCRIPTOR DATACREDITO', '440702');
*/